
trigger: none

pool:
  name: 'Agent Pool Name'

variables:
  vnetname: 'example'
  subnetname: ''
  location: 'westeurope'


stages:
- stage: CreateResourceGroup
  jobs:
  - job: CreateResourceGroup
    steps:

- stage: CreateVirtualNetwork
  jobs:
  - job: DeployBicepTemplate
    steps:
